// File: mask_lut.v
// Generated by MyHDL 0.10
// Date: Wed Nov 21 18:38:39 2018


`timescale 1ns/10ps

module mask_lut (
    char_in,
    mask_out,
    reset_n
);


input [7:0] char_in;
output [2:0] mask_out;
wire [2:0] mask_out;
input reset_n;

wire [2:0] mask_table [0:128-1];




assign mask_out = mask_table[char_in];

endmodule
